"""dispersiones_y_recibos

Revision ID: 13d00ad10c72
Revises: 83b07dc3f704
Create Date: 2024-03-26 00:53:21.104534

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '13d00ad10c72'
down_revision: Union[str, None] = '83b07dc3f704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispersiones',
                    sa.Column('id_dispersion', sa.Integer(), nullable=False),
                    sa.Column('fecha', sa.Date(),
                              server_default=sa.text('(CURRENT_DATE)'),
                              nullable=True),
                    sa.Column('periodo', sa.Integer(), nullable=True),
                    sa.Column('periodo_fecha', sa.Date(), nullable=True),
                    sa.Column('total', sa.Float(), nullable=True),
                    sa.Column('id_usuario', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['id_usuario'],
                                            ['users.id_user'], ),
                    sa.PrimaryKeyConstraint('id_dispersion')
                    )
    op.create_index(op.f('ix_dispersiones_id_dispersion'),
                    'dispersiones',
                    ['id_dispersion'],
                    unique=False)
    op.create_table('cuentas',
                    sa.Column('id_cuenta', sa.Integer(), nullable=False),
                    sa.Column('fecha',
                              sa.Date(),
                              server_default=sa.text('(CURRENT_DATE)'),
                              nullable=True),
                    sa.Column('numero', sa.String(), nullable=True),
                    sa.Column('tipo', sa.Integer(), nullable=True),
                    sa.Column('activa', sa.Boolean(), nullable=True),
                    sa.Column('id_banco', sa.Integer(), nullable=True),
                    sa.Column('id_empleado', sa.Integer(), nullable=True),
                    sa.Column('id_usuario', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['id_banco'],
                                            ['bancos.id_banco'], ),
                    sa.ForeignKeyConstraint(['id_empleado'],
                                            ['empleados.id_empleado'], ),
                    sa.ForeignKeyConstraint(['id_usuario'],
                                            ['users.id_user'], ),
                    sa.PrimaryKeyConstraint('id_cuenta')
                    )
    op.create_index(op.f('ix_cuentas_id_cuenta'),
                    'cuentas',
                    ['id_cuenta'],
                    unique=False)
    op.create_table('recibos',
                    sa.Column('id_recibo', sa.Integer(), nullable=False),
                    sa.Column('id_empleado', sa.Integer(), nullable=True),
                    sa.Column('id_dispersion', sa.Integer(), nullable=True),
                    sa.Column('monto', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['id_dispersion'],
                                            ['dispersiones.id_dispersion'], ),
                    sa.ForeignKeyConstraint(['id_empleado'],
                                            ['empleados.id_empleado'], ),
                    sa.PrimaryKeyConstraint('id_recibo')
                    )
    op.create_index(op.f('ix_recibos_id_recibo'),
                    'recibos',
                    ['id_recibo'],
                    unique=False)
    op.create_table('dispersiones_detalle',
                    sa.Column('id_dispersiones_detalle',
                              sa.Integer(),
                              nullable=False),
                    sa.Column('id_dispersion', sa.Integer(), nullable=True),
                    sa.Column('id_cuenta', sa.Integer(), nullable=True),
                    sa.Column('monto', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['id_cuenta'],
                                            ['cuentas.id_cuenta'], ),
                    sa.ForeignKeyConstraint(['id_dispersion'],
                                            ['dispersiones.id_dispersion'], ),
                    sa.PrimaryKeyConstraint('id_dispersiones_detalle')
                    )
    op.create_index(op.f('ix_dispersiones_detalle_id_dispersiones_detalle'),
                    'dispersiones_detalle',
                    ['id_dispersiones_detalle'],
                    unique=False)
    op.create_table('recibos_detalle',
                    sa.Column('id_recibos_detalle',
                              sa.Integer(),
                              nullable=False),
                    sa.Column('id_recibo', sa.Integer(), nullable=False),
                    sa.Column('id_ajuste', sa.Integer(), nullable=True),
                    sa.Column('id_prestamo', sa.Integer(), nullable=True),
                    sa.Column('id_salario', sa.Integer(), nullable=True),
                    sa.Column('id_cuenta', sa.Integer(), nullable=True),
                    sa.Column('texto', sa.String(), nullable=True),
                    sa.Column('monto', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(['id_ajuste'],
                                            ['ajustes.id_ajuste'], ),
                    sa.ForeignKeyConstraint(['id_cuenta'],
                                            ['cuentas.id_cuenta'], ),
                    sa.ForeignKeyConstraint(['id_prestamo'],
                                            ['prestamos.id_prestamo'], ),
                    sa.ForeignKeyConstraint(['id_recibo'],
                                            ['recibos.id_recibo'], ),
                    sa.ForeignKeyConstraint(['id_salario'],
                                            ['salarios.id_salario'], ),
                    sa.PrimaryKeyConstraint('id_recibos_detalle')
                    )
    op.create_index(op.f('ix_recibos_detalle_id_recibos_detalle'),
                    'recibos_detalle',
                    ['id_recibos_detalle'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recibos_detalle_id_recibos_detalle'),
                  table_name='recibos_detalle')
    op.drop_table('recibos_detalle')
    op.drop_index(op.f('ix_dispersiones_detalle_id_dispersiones_detalle'),
                  table_name='dispersiones_detalle')
    op.drop_table('dispersiones_detalle')
    op.drop_index(op.f('ix_recibos_id_recibo'), table_name='recibos')
    op.drop_table('recibos')
    op.drop_index(op.f('ix_cuentas_id_cuenta'), table_name='cuentas')
    op.drop_table('cuentas')
    op.drop_index(op.f('ix_dispersiones_id_dispersion'),
                  table_name='dispersiones')
    op.drop_table('dispersiones')
    # ### end Alembic commands ###
