"""initial migration

Revision ID: ee3bdba69f8a
Revises:
Create Date: 2024-03-19 23:13:18.010747

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ee3bdba69f8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bancos',
                    sa.Column('id_banco', sa.Integer(), nullable=False),
                    sa.Column('nombre', sa.String(), nullable=True),
                    sa.Column('activo', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id_banco'),
                    sa.UniqueConstraint('nombre')
                    )
    op.create_index(op.f('ix_bancos_id_banco'), 'bancos', ['id_banco'],
                    unique=False)
    op.create_table('colonias',
                    sa.Column('id_colonia', sa.Integer(), nullable=False),
                    sa.Column('nombre', sa.String(), nullable=True),
                    sa.Column('ciudad', sa.String(), nullable=True),
                    sa.Column('estado', sa.String(), nullable=True),
                    sa.Column('cp', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id_colonia')
                    )
    op.create_index(op.f('ix_colonias_cp'), 'colonias', ['cp'], unique=False)
    op.create_index(op.f('ix_colonias_id_colonia'),
                    'colonias',
                    ['id_colonia'],
                    unique=False)
    op.create_table('users',
                    sa.Column('id_user', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('nombre', sa.String(), nullable=True),
                    sa.Column('password_h', sa.String(), nullable=True),
                    sa.Column('scopes', sa.String(), nullable=True),
                    sa.Column('activo', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id_user'),
                    sa.UniqueConstraint('username')
                    )
    op.create_index(op.f('ix_users_id_user'),
                    'users',
                    ['id_user'],
                    unique=False)
    op.create_table('empleados',
                    sa.Column('id_empleado', sa.Integer(), nullable=False),
                    sa.Column('nombre', sa.String(), nullable=True),
                    sa.Column('paterno', sa.String(), nullable=True),
                    sa.Column('materno', sa.String(), nullable=True),
                    sa.Column('rfc', sa.String(), nullable=True),
                    sa.Column('curp', sa.String(), nullable=True),
                    sa.Column('calle', sa.String(), nullable=True),
                    sa.Column('exterior', sa.String(), nullable=True),
                    sa.Column('interior', sa.String(), nullable=True),
                    sa.Column('id_colonia', sa.Integer(), nullable=True),
                    sa.Column('telefono', sa.String(), nullable=True),
                    sa.Column('celular', sa.String(), nullable=True),
                    sa.Column('activo', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['id_colonia'],
                                            ['colonias.id_colonia'], ),
                    sa.PrimaryKeyConstraint('id_empleado'),
                    sa.UniqueConstraint('curp'),
                    sa.UniqueConstraint('rfc')
                    )
    op.create_index(op.f('ix_empleados_id_empleado'), 'empleados',
                    ['id_empleado'], unique=False)
    op.create_table('ajustes',
                    sa.Column('id_ajuste', sa.Integer(), nullable=False),
                    sa.Column('fecha', sa.Date(),
                              server_default=sa.text('(CURRENT_DATE)'),
                              nullable=True),
                    sa.Column('fecha_inicio', sa.Date(), nullable=True),
                    sa.Column('fecha_fin', sa.Date(), nullable=True),
                    sa.Column('motivo', sa.String(), nullable=True),
                    sa.Column('monto', sa.Float(), nullable=True),
                    sa.Column('id_empleado', sa.Integer(), nullable=True),
                    sa.Column('id_usuario', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['id_empleado'],
                                            ['empleados.id_empleado'], ),
                    sa.ForeignKeyConstraint(['id_usuario'],
                                            ['users.id_user'], ),
                    sa.PrimaryKeyConstraint('id_ajuste')
                    )
    op.create_index(op.f('ix_ajustes_id_ajuste'),
                    'ajustes',
                    ['id_ajuste'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ajustes_id_ajuste'), table_name='ajustes')
    op.drop_table('ajustes')
    op.drop_index(op.f('ix_empleados_id_empleado'), table_name='empleados')
    op.drop_table('empleados')
    op.drop_index(op.f('ix_users_id_user'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_colonias_id_colonia'), table_name='colonias')
    op.drop_index(op.f('ix_colonias_cp'), table_name='colonias')
    op.drop_table('colonias')
    op.drop_index(op.f('ix_bancos_id_banco'), table_name='bancos')
    op.drop_table('bancos')
    # ### end Alembic commands ###
